- name: execting
  hosts: local
  connection: local
  vars:
    Greet: "Hi sai"
  
  vars_files:
  - vars.yaml

  vars_prompt:
  - name: Greeting are
    prompt: Enter the value
    private: false
    
  tasks:
  - name: Greetings
    ansible.builtin.debug:
      msg: "Greetings are {{ Greet }}"