- name: installing  nginx
  hosts: webs
  tasks:
  - name: installing nginx
    ansible.builtin.dnf:
      name: nginx
      state: installed
    when: ansible_os_family == "RedHat"

  - name: installing nginx
    ansible.builtin.apt:
      name: nginx
      state: installed
    when: ansible_os_family == "Debian"