- name: installing packages
  hosts: webs
  become: yes
  tasks:
  - name: installing packages
    ansible.builtin.packages:
      name: "{{ item }}"
      state: installed
    loop:
    - git
    - mysql
    - gcc
    - zip