- name: EXecuting
  hosts: local
  connection: local
  vars_files:
  - vars.yaml
  tasks:
  - name: print course information
    ansible.builtin.package:
      msg: "course is {{ COURSE }}, duration is {{ Duration }}, student is {{ Student }}"
