- name: EXecuting
  hosts: local
  connection: local
  vars_files:
  - vars.yaml
  tasks:
  - name: print course information
    ansible.builtin.debug:
      msg: "course is {{ COURSE }}, duration is {{ Duration }}, student is {{ Student }}"

- name: EXecuting
  hosts: local
  connection: local
  vars_prompt:
  - name: Duration
    prompt: This course is job oriented
    private: false
  - name: COURSE
    prompt: please enter course name
    private: false
  - name: Student
    prompt: student is
    private: false
  tasks:
  - name: print course information
    ansible.builtin.debug:
      msg: "course is {{ COURSE }}, duration is {{ Duration }}, student is {{ Student }}"
